### ISSUE TITLE
THANKYOU. CAN I REQUEST INDONESIAN SUBTITLE OPTION TO DOWNLOAD?

### ISSUE THREAD

**Issue by fakartstore** [georgetian3/viki-download#1]
THANKYOU. CAN I REQUEST INDONESIAN SUBTITLE OPTION TO DOWNLOAD?

**Comment by georgetian3** [comment]
> THANKYOU. CAN I REQUEST INDONESIAN SUBTITLE OPTION TO DOWNLOAD?

Hi fakartstore, 

I'll add Indonesian as soon as possible.

However, please note the the program is a tad buggy. It downloads each episode assuming each episode's video source URL has consecutive numbering. However, I found this to not be the case, especially in longer drama series.
